export const LOAD_PAGES_REQUEST = 'LOAD_PAGES_REQUEST'
export const LOAD_PAGES_SUCCESS = 'LOAD_PAGES_SUCCESS'
export const LOAD_PAGES_FAILURE = 'LOAD_PAGES_FAILURE'

export const LOAD_PAGE_REQUEST = 'LOAD_PAGE_REQUEST'
export const LOAD_PAGE_SUCCESS = 'LOAD_PAGE_SUCCESS'
export const LOAD_PAGE_FAILURE = 'LOAD_PAGE_FAILURE'

export const CREATE_PAGE_REQUEST = 'CREATE_PAGE_REQUEST'
export const CREATE_PAGE_SUCCESS = 'CREATE_PAGE_SUCCESS'
export const CREATE_PAGE_FAILURE = 'CREATE_PAGE_FAILURE'

export const DELETE_PAGE_REQUEST = 'DELETE_PAGE_REQUEST'
export const DELETE_PAGE_SUCCESS = 'DELETE_PAGE_SUCCESS'
export const DELETE_PAGE_FAILURE = 'DELETE_PAGE_FAILURE'

export const UPDATE_PAGE_REQUEST = 'UPDATE_PAGE_REQUEST'
export const UPDATE_PAGE_SUCCESS = 'UPDATE_PAGE_SUCCESS'
export const UPDATE_PAGE_FAILURE = 'UPDATE_PAGE_FAILURE'


export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
export const LOAD_USERS_FAILURE = 'LOAD_USERS_FAILURE'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE'

export const LOAD_DATAS_REQUEST = 'LOAD_DATAS_REQUEST'
export const LOAD_DATAS_SUCCESS = 'LOAD_DATAS_SUCCESS'
export const LOAD_DATAS_FAILURE = 'LOAD_DATAS_FAILURE'

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST'
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS'
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'


export const LOAD_ROOMSCOL_REQUEST='LOAD_ROOMSCOL_REQUEST'
export const LOAD_ROOMSCOL_SUCCESS='LOAD_ROOMSCOL_SUCCESS'
export const LOAD_ROOMSCOL_FAILURE='LOAD_ROOMSCOL_FAILURE'

export const LOAD_ROOMCOL_REQUEST='LOAD_ROOMCOL_REQUEST'
export const LOAD_ROOMCOL_SUCCESS='LOAD_ROOMCOL_SUCCESS'
export const LOAD_ROOMCOL_FAILURE='LOAD_ROOMCOL_FAILURE'

export const CREATE_ROOMSCOL_REQUEST='CREATE_ROOMSCOL_REQUEST'
export const CREATE_ROOMSCOL_SUCCESS='CREATE_ROOMSCOL_SUCCESS'
export const CREATE_ROOMSCOL_FAILURE='CREATE_ROOMSCOL_FAILURE'

export const CREATE_ROOMS_REQUEST='CREATE_ROOMS_REQUEST'
export const CREATE_ROOMS_SUCCESS='CREATE_ROOMS_SUCCESS'
export const CREATE_ROOMS_FAILURE='CREATE_ROOMS_FAILURE'

export const DELETE_ROOMS_REQUEST='DELETE_ROOMS_REQUEST'
export const DELETE_ROOMS_SUCCESS='DELETE_ROOMS_SUCCESS'
export const DELETE_ROOMS_FAILURE='DELETE_ROOMS_FAILURE'

export const DELETE_ROOMSCOL_REQUEST='DELETE_ROOMSCOL_REQUEST'
export const DELETE_ROOMSCOL_SUCCESS='DELETE_ROOMSCOL_SUCCESS'
export const DELETE_ROOMSCOL_FAILURE='DELETE_ROOMSCOL_FAILURE'

export const LOAD_ROOMS_REQUEST = 'LOAD_ROOMS_REQUEST'
export const LOAD_ROOMS_SUCCESS = 'LOAD_ROOMS_SUCCESS'
export const LOAD_ROOMS_FAILURE = 'LOAD_ROOMS_FAILURE'

export const CREATE_RESERVE_REQUEST = 'CREATE_RESERVE_REQUEST'
export const CREATE_RESERVE_SUCCESS = 'CREATE_RESERVE_SUCCESS'
export const CREATE_RESERVE_FAILURE = 'CREATE_RESERVE_FAILURE'

export const LOAD_RESERVE_REQUEST = 'LOAD_RESERVE_REQUEST'
export const LOAD_RESERVE_SUCCESS = 'LOAD_RESERVE_SUCCESS'
export const LOAD_RESERVE_FAILURE = 'LOAD_RESERVE_FAILURE'

export const DELETE_RESERVE_REQUEST='DELETE_RESERVE_REQUEST'
export const DELETE_RESERVE_SUCCESS='DELETE_RESERVE_SUCCESS'
export const DELETE_RESERVE_FAILURE='DELETE_RESERVE_FAILURE'

export const RESET_PASSWORD_REQUEST='RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAILURE='RESET_PASSWORD_FAILURE'